language: php
php:
    - 7.0

script:
    - vendor/bin/tester tests -p php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer install --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

